/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MovieNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_TEMPLATE = `---
title: {{title}}
original_title: {{original_title}}
release_date: {{release_date}}
director: {{director}}
runtime: {{runtime}}
genres: {{genres}}
rating: {{vote_average}}
tmdb_id: {{tmdb_id}}
imdb_id: {{imdb_id}}
---

# {{title}}

![\u30DD\u30B9\u30BF\u30FC]({{poster_url}})

## \u57FA\u672C\u60C5\u5831

- **\u539F\u984C**: {{original_title}}
- **\u516C\u958B\u65E5**: {{release_date}}
- **\u76E3\u7763**: {{director}}
- **\u4E0A\u6620\u6642\u9593**: {{runtime_formatted}}
- **\u30B8\u30E3\u30F3\u30EB**: {{genres}}
- **\u8A55\u4FA1**: \u2B50 {{vote_average}}/10 ({{vote_count}}\u7968)

## \u30AD\u30E3\u30B9\u30C8

{{cast_list}}

## \u3042\u3089\u3059\u3058

{{overview}}

## \u30E1\u30E2

<!-- \u3053\u3053\u306B\u611F\u60F3\u3084\u30E1\u30E2\u3092\u66F8\u3044\u3066\u304F\u3060\u3055\u3044 -->

---
*\u3053\u306E\u30CE\u30FC\u30C8\u306F [TMDb]({{tmdb_url}}) \u304B\u3089\u81EA\u52D5\u751F\u6210\u3055\u308C\u307E\u3057\u305F\u3002*
`;
var DEFAULT_SETTINGS = {
  apiKey: "",
  outputFolder: "Movies",
  language: "ja-JP",
  noteTemplate: DEFAULT_TEMPLATE
};
var MovieNotePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("film", "Movie Note", () => {
      this.openMovieSearch();
    });
    this.addCommand({
      id: "search-movie",
      name: "Search Movie",
      callback: () => {
        this.openMovieSearch();
      }
    });
    this.addSettingTab(new MovieNoteSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // 映画検索モーダルを開く
  openMovieSearch() {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("TMDb API\u30AD\u30FC\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u8A2D\u5B9A\u304B\u3089\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    new MovieSearchModal(this.app, this).open();
  }
  // TMDb APIで映画を検索
  async searchMovies(query) {
    const { apiKey, language } = this.settings;
    const searchUrl = `https://api.themoviedb.org/3/search/movie?api_key=${apiKey}&query=${encodeURIComponent(query)}&language=${language}`;
    try {
      const response = await (0, import_obsidian.requestUrl)(searchUrl);
      return response.json.results || [];
    } catch (error) {
      console.error("\u6620\u753B\u691C\u7D22\u30A8\u30E9\u30FC:", error);
      new import_obsidian.Notice("\u6620\u753B\u306E\u691C\u7D22\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      return [];
    }
  }
  // 映画の詳細情報を取得
  async getMovieDetails(movieId) {
    const { apiKey, language } = this.settings;
    const detailUrl = `https://api.themoviedb.org/3/movie/${movieId}?api_key=${apiKey}&language=${language}&append_to_response=credits`;
    try {
      const response = await (0, import_obsidian.requestUrl)(detailUrl);
      return response.json;
    } catch (error) {
      console.error("\u6620\u753B\u8A73\u7D30\u53D6\u5F97\u30A8\u30E9\u30FC:", error);
      new import_obsidian.Notice("\u6620\u753B\u306E\u8A73\u7D30\u60C5\u5831\u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      return null;
    }
  }
  // 映画ノートを作成
  async createMovieNote(movie) {
    const { outputFolder } = this.settings;
    const year = movie.release_date ? movie.release_date.split("-")[0] : "Unknown";
    const fileName = `${movie.title} (${year}).md`;
    const filePath = `${outputFolder}/${fileName}`;
    const folder = this.app.vault.getAbstractFileByPath(outputFolder);
    if (!folder) {
      await this.app.vault.createFolder(outputFolder);
    }
    const content = this.generateNoteContent(movie);
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);
    if (existingFile) {
      new import_obsidian.Notice(`\u30CE\u30FC\u30C8\u300C${fileName}\u300D\u306F\u65E2\u306B\u5B58\u5728\u3057\u307E\u3059\u3002`);
      return;
    }
    try {
      await this.app.vault.create(filePath, content);
      new import_obsidian.Notice(`\u30CE\u30FC\u30C8\u300C${fileName}\u300D\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F\uFF01`);
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file) {
        await this.app.workspace.getLeaf().openFile(file);
      }
    } catch (error) {
      console.error("\u30CE\u30FC\u30C8\u4F5C\u6210\u30A8\u30E9\u30FC:", error);
      new import_obsidian.Notice("\u30CE\u30FC\u30C8\u306E\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
    }
  }
  // ノートの内容を生成（テンプレート変数を置換）
  generateNoteContent(movie) {
    const template = this.settings.noteTemplate;
    const variables = this.createTemplateVariables(movie);
    let content = template;
    for (const [key, value] of Object.entries(variables)) {
      const regex = new RegExp(`{{${key}}}`, "g");
      content = content.replace(regex, value);
    }
    return content;
  }
  // テンプレート変数を作成
  createTemplateVariables(movie) {
    var _a, _b, _c, _d, _e, _f, _g;
    const year = movie.release_date ? movie.release_date.split("-")[0] : "";
    const runtime = movie.runtime || 0;
    const hours = Math.floor(runtime / 60);
    const minutes = runtime % 60;
    const runtimeFormatted = runtime ? `${hours}\u6642\u9593${minutes}\u5206` : "\u4E0D\u660E";
    const directors = movie.credits.crew.filter((p) => p.job === "Director").map((p) => p.name);
    const writers = movie.credits.crew.filter((p) => p.job === "Screenplay" || p.job === "Writer").map((p) => p.name);
    const producers = movie.credits.crew.filter((p) => p.job === "Producer").map((p) => p.name);
    const castTop5 = movie.credits.cast.slice(0, 5).map((p) => p.name).join(", ");
    const castTop10 = movie.credits.cast.slice(0, 10).map((p) => p.name).join(", ");
    const castList = movie.credits.cast.slice(0, 10).map((p) => `- ${p.name} (${p.character})`).join("\n");
    const genres = movie.genres.map((g) => g.name).join(", ");
    const genresList = movie.genres.map((g) => `- ${g.name}`).join("\n");
    const genreIds = movie.genres.map((g) => g.id).join(", ");
    const productionCompanies = movie.production_companies.map((c) => c.name).join(", ");
    const productionCountries = movie.production_countries.map((c) => c.name).join(", ");
    const spokenLanguages = movie.spoken_languages.map((l) => l.name).join(", ");
    const budgetFormatted = movie.budget ? `$${movie.budget.toLocaleString()}` : "\u4E0D\u660E";
    const revenueFormatted = movie.revenue ? `$${movie.revenue.toLocaleString()}` : "\u4E0D\u660E";
    const posterUrl = movie.poster_path ? `https://image.tmdb.org/t/p/w500${movie.poster_path}` : "";
    const posterUrlOriginal = movie.poster_path ? `https://image.tmdb.org/t/p/original${movie.poster_path}` : "";
    const backdropUrl = movie.backdrop_path ? `https://image.tmdb.org/t/p/w1280${movie.backdrop_path}` : "";
    const backdropUrlOriginal = movie.backdrop_path ? `https://image.tmdb.org/t/p/original${movie.backdrop_path}` : "";
    const tmdbUrl = `https://www.themoviedb.org/movie/${movie.id}`;
    const imdbUrl = movie.imdb_id ? `https://www.imdb.com/title/${movie.imdb_id}` : "";
    const collectionName = ((_a = movie.belongs_to_collection) == null ? void 0 : _a.name) || "";
    const collectionId = ((_b = movie.belongs_to_collection) == null ? void 0 : _b.id.toString()) || "";
    return {
      // 基本情報
      "title": movie.title || "",
      "original_title": movie.original_title || "",
      "tagline": movie.tagline || "",
      "overview": movie.overview || "\u3042\u3089\u3059\u3058\u60C5\u5831\u304C\u3042\u308A\u307E\u305B\u3093\u3002",
      "release_date": movie.release_date || "",
      "year": year,
      "status": movie.status || "",
      "runtime": runtime.toString(),
      "runtime_formatted": runtimeFormatted,
      // 評価・人気度
      "vote_average": ((_c = movie.vote_average) == null ? void 0 : _c.toString()) || "0",
      "vote_count": ((_d = movie.vote_count) == null ? void 0 : _d.toString()) || "0",
      "popularity": ((_e = movie.popularity) == null ? void 0 : _e.toString()) || "0",
      // ジャンル
      "genres": genres,
      "genres_list": genresList,
      "genre_ids": genreIds,
      // 制作情報
      "budget": ((_f = movie.budget) == null ? void 0 : _f.toString()) || "0",
      "budget_formatted": budgetFormatted,
      "revenue": ((_g = movie.revenue) == null ? void 0 : _g.toString()) || "0",
      "revenue_formatted": revenueFormatted,
      "production_companies": productionCompanies,
      "production_countries": productionCountries,
      "spoken_languages": spokenLanguages,
      // スタッフ
      "director": directors[0] || "\u4E0D\u660E",
      "directors": directors.join(", "),
      "writer": writers[0] || "",
      "writers": writers.join(", "),
      "producer": producers[0] || "",
      "producers": producers.join(", "),
      // キャスト
      "cast_top5": castTop5,
      "cast_top10": castTop10,
      "cast_list": castList,
      // 画像
      "poster_url": posterUrl,
      "poster_url_original": posterUrlOriginal,
      "backdrop_url": backdropUrl,
      "backdrop_url_original": backdropUrlOriginal,
      // リンク・ID
      "tmdb_id": movie.id.toString(),
      "imdb_id": movie.imdb_id || "",
      "tmdb_url": tmdbUrl,
      "imdb_url": imdbUrl,
      "homepage": movie.homepage || "",
      // コレクション
      "collection_name": collectionName,
      "collection_id": collectionId,
      // その他
      "adult": movie.adult ? "true" : "false",
      "video": movie.video ? "true" : "false",
      "original_language": movie.original_language || ""
    };
  }
};
var MovieSearchModal = class extends import_obsidian.SuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("\u6620\u753B\u30BF\u30A4\u30C8\u30EB\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044...");
  }
  // 入力に基づいて候補を取得
  async getSuggestions(query) {
    if (query.length < 2) {
      return [];
    }
    return await this.plugin.searchMovies(query);
  }
  // 候補の表示内容をカスタマイズ
  renderSuggestion(movie, el) {
    el.createEl("div", { text: movie.title, cls: "movie-title" });
    const details = el.createEl("div", { cls: "movie-details" });
    if (movie.original_title !== movie.title) {
      details.createEl("span", { text: movie.original_title, cls: "movie-original-title" });
    }
    if (movie.release_date) {
      const year = movie.release_date.split("-")[0];
      details.createEl("span", { text: ` (${year})`, cls: "movie-year" });
    }
    if (movie.overview) {
      el.createEl("div", {
        text: movie.overview.substring(0, 100) + "...",
        cls: "movie-overview"
      });
    }
  }
  // 選択時の処理
  async onChooseSuggestion(movie, evt) {
    new import_obsidian.Notice(`\u300C${movie.title}\u300D\u306E\u60C5\u5831\u3092\u53D6\u5F97\u4E2D...`);
    const movieDetails = await this.plugin.getMovieDetails(movie.id);
    if (movieDetails) {
      await this.plugin.createMovieNote(movieDetails);
    }
  }
};
var MovieNoteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Movie Note Plugin \u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("TMDb API\u30AD\u30FC").setDesc("TMDb\u304B\u3089\u53D6\u5F97\u3057\u305FAPI\u30AD\u30FC\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addText((text) => text.setPlaceholder("API\u30AD\u30FC\u3092\u5165\u529B").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("a", {
      text: "TMDb API\u30AD\u30FC\u3092\u53D6\u5F97\u3059\u308B",
      href: "https://www.themoviedb.org/settings/api"
    });
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u6620\u753B\u30CE\u30FC\u30C8\u3092\u4FDD\u5B58\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u30D1\u30B9\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addText((text) => text.setPlaceholder("Movies").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u8A00\u8A9E").setDesc("\u30E1\u30BF\u30C7\u30FC\u30BF\u306E\u8A00\u8A9E\u3092\u8A2D\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addDropdown((dropdown) => dropdown.addOption("ja-JP", "\u65E5\u672C\u8A9E").addOption("en-US", "English").addOption("ko-KR", "\uD55C\uAD6D\uC5B4").addOption("zh-CN", "\u4E2D\u6587\uFF08\u7B80\u4F53\uFF09").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u30CE\u30FC\u30C8\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8" });
    containerEl.createEl("p", {
      text: "\u5229\u7528\u53EF\u80FD\u306A\u5909\u6570\u306E\u4E00\u89A7\u306F ",
      cls: "setting-item-description"
    }).createEl("a", {
      text: "TMDB_DATA_REFERENCE.md",
      href: "https://github.com/KxOxUxMxExI/obsidian-movie-note/blob/main/TMDB_DATA_REFERENCE.md"
    });
    new import_obsidian.Setting(containerEl).setName("\u30AB\u30B9\u30BF\u30E0\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8").setDesc("{{\u5909\u6570\u540D}} \u306E\u5F62\u5F0F\u3067\u5909\u6570\u3092\u4F7F\u7528\u3067\u304D\u307E\u3059\u3002").addTextArea((text) => {
      text.setPlaceholder("\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u3092\u5165\u529B...").setValue(this.plugin.settings.noteTemplate).onChange(async (value) => {
        this.plugin.settings.noteTemplate = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 20;
      text.inputEl.cols = 60;
      text.inputEl.style.fontFamily = "monospace";
      text.inputEl.style.fontSize = "12px";
    });
    new import_obsidian.Setting(containerEl).setName("\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u3092\u30EA\u30BB\u30C3\u30C8").setDesc("\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u3092\u30C7\u30D5\u30A9\u30EB\u30C8\u306B\u623B\u3057\u307E\u3059\u3002").addButton((button) => button.setButtonText("\u30C7\u30D5\u30A9\u30EB\u30C8\u306B\u623B\u3059").onClick(async () => {
      this.plugin.settings.noteTemplate = DEFAULT_TEMPLATE;
      await this.plugin.saveSettings();
      this.display();
      new import_obsidian.Notice("\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u3092\u30C7\u30D5\u30A9\u30EB\u30C8\u306B\u623B\u3057\u307E\u3057\u305F\u3002");
    }));
  }
};
