/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MovieNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  outputFolder: "Movies",
  language: "ja-JP"
};
var MovieNotePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("film", "Movie Note", () => {
      this.openMovieSearch();
    });
    this.addCommand({
      id: "search-movie",
      name: "Search Movie",
      callback: () => {
        this.openMovieSearch();
      }
    });
    this.addSettingTab(new MovieNoteSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // 映画検索モーダルを開く
  openMovieSearch() {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("TMDb API\u30AD\u30FC\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u8A2D\u5B9A\u304B\u3089\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    new MovieSearchModal(this.app, this).open();
  }
  // TMDb APIで映画を検索
  async searchMovies(query) {
    const { apiKey, language } = this.settings;
    const searchUrl = `https://api.themoviedb.org/3/search/movie?api_key=${apiKey}&query=${encodeURIComponent(query)}&language=${language}`;
    try {
      const response = await (0, import_obsidian.requestUrl)(searchUrl);
      return response.json.results || [];
    } catch (error) {
      console.error("\u6620\u753B\u691C\u7D22\u30A8\u30E9\u30FC:", error);
      new import_obsidian.Notice("\u6620\u753B\u306E\u691C\u7D22\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      return [];
    }
  }
  // 映画の詳細情報を取得
  async getMovieDetails(movieId) {
    const { apiKey, language } = this.settings;
    const detailUrl = `https://api.themoviedb.org/3/movie/${movieId}?api_key=${apiKey}&language=${language}&append_to_response=credits`;
    try {
      const response = await (0, import_obsidian.requestUrl)(detailUrl);
      return response.json;
    } catch (error) {
      console.error("\u6620\u753B\u8A73\u7D30\u53D6\u5F97\u30A8\u30E9\u30FC:", error);
      new import_obsidian.Notice("\u6620\u753B\u306E\u8A73\u7D30\u60C5\u5831\u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      return null;
    }
  }
  // 映画ノートを作成
  async createMovieNote(movie) {
    const { outputFolder } = this.settings;
    const year = movie.release_date ? movie.release_date.split("-")[0] : "Unknown";
    const fileName = `${movie.title} (${year}).md`;
    const filePath = `${outputFolder}/${fileName}`;
    const folder = this.app.vault.getAbstractFileByPath(outputFolder);
    if (!folder) {
      await this.app.vault.createFolder(outputFolder);
    }
    const content = this.generateNoteContent(movie);
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);
    if (existingFile) {
      new import_obsidian.Notice(`\u30CE\u30FC\u30C8\u300C${fileName}\u300D\u306F\u65E2\u306B\u5B58\u5728\u3057\u307E\u3059\u3002`);
      return;
    }
    try {
      await this.app.vault.create(filePath, content);
      new import_obsidian.Notice(`\u30CE\u30FC\u30C8\u300C${fileName}\u300D\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F\uFF01`);
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file) {
        await this.app.workspace.getLeaf().openFile(file);
      }
    } catch (error) {
      console.error("\u30CE\u30FC\u30C8\u4F5C\u6210\u30A8\u30E9\u30FC:", error);
      new import_obsidian.Notice("\u30CE\u30FC\u30C8\u306E\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
    }
  }
  // ノートの内容を生成
  generateNoteContent(movie) {
    var _a;
    const posterUrl = movie.poster_path ? `https://image.tmdb.org/t/p/w500${movie.poster_path}` : "";
    const director = ((_a = movie.credits.crew.find((person) => person.job === "Director")) == null ? void 0 : _a.name) || "\u4E0D\u660E";
    const cast = movie.credits.cast.slice(0, 5).map((person) => person.name).join(", ");
    const genres = movie.genres.map((g) => g.name).join(", ");
    const runtime = movie.runtime ? `${movie.runtime}\u5206` : "\u4E0D\u660E";
    return `---
title: ${movie.title}
original_title: ${movie.original_title}
release_date: ${movie.release_date}
director: ${director}
runtime: ${runtime}
genres: ${genres}
rating: ${movie.vote_average}
tmdb_id: ${movie.id}
---

# ${movie.title}

![\u30DD\u30B9\u30BF\u30FC](${posterUrl})

## \u57FA\u672C\u60C5\u5831

- **\u539F\u984C**: ${movie.original_title}
- **\u516C\u958B\u65E5**: ${movie.release_date}
- **\u76E3\u7763**: ${director}
- **\u4E0A\u6620\u6642\u9593**: ${runtime}
- **\u30B8\u30E3\u30F3\u30EB**: ${genres}
- **\u8A55\u4FA1**: \u2B50 ${movie.vote_average}/10

## \u30AD\u30E3\u30B9\u30C8

${cast}

## \u3042\u3089\u3059\u3058

${movie.overview || "\u3042\u3089\u3059\u3058\u60C5\u5831\u304C\u3042\u308A\u307E\u305B\u3093\u3002"}

## \u30E1\u30E2

<!-- \u3053\u3053\u306B\u611F\u60F3\u3084\u30E1\u30E2\u3092\u66F8\u3044\u3066\u304F\u3060\u3055\u3044 -->

---
*\u3053\u306E\u30CE\u30FC\u30C8\u306F [TMDb](https://www.themoviedb.org/movie/${movie.id}) \u304B\u3089\u81EA\u52D5\u751F\u6210\u3055\u308C\u307E\u3057\u305F\u3002*
`;
  }
};
var MovieSearchModal = class extends import_obsidian.SuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("\u6620\u753B\u30BF\u30A4\u30C8\u30EB\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044...");
  }
  // 入力に基づいて候補を取得
  async getSuggestions(query) {
    if (query.length < 2) {
      return [];
    }
    return await this.plugin.searchMovies(query);
  }
  // 候補の表示内容をカスタマイズ
  renderSuggestion(movie, el) {
    el.createEl("div", { text: movie.title, cls: "movie-title" });
    const details = el.createEl("div", { cls: "movie-details" });
    if (movie.original_title !== movie.title) {
      details.createEl("span", { text: movie.original_title, cls: "movie-original-title" });
    }
    if (movie.release_date) {
      const year = movie.release_date.split("-")[0];
      details.createEl("span", { text: ` (${year})`, cls: "movie-year" });
    }
    if (movie.overview) {
      el.createEl("div", {
        text: movie.overview.substring(0, 100) + "...",
        cls: "movie-overview"
      });
    }
  }
  // 選択時の処理
  async onChooseSuggestion(movie, evt) {
    new import_obsidian.Notice(`\u300C${movie.title}\u300D\u306E\u60C5\u5831\u3092\u53D6\u5F97\u4E2D...`);
    const movieDetails = await this.plugin.getMovieDetails(movie.id);
    if (movieDetails) {
      await this.plugin.createMovieNote(movieDetails);
    }
  }
};
var MovieNoteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Movie Note Plugin \u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("TMDb API\u30AD\u30FC").setDesc("TMDb\u304B\u3089\u53D6\u5F97\u3057\u305FAPI\u30AD\u30FC\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addText((text) => text.setPlaceholder("API\u30AD\u30FC\u3092\u5165\u529B").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("a", {
      text: "TMDb API\u30AD\u30FC\u3092\u53D6\u5F97\u3059\u308B",
      href: "https://www.themoviedb.org/settings/api"
    });
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u6620\u753B\u30CE\u30FC\u30C8\u3092\u4FDD\u5B58\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u30D1\u30B9\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addText((text) => text.setPlaceholder("Movies").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u8A00\u8A9E").setDesc("\u30E1\u30BF\u30C7\u30FC\u30BF\u306E\u8A00\u8A9E\u3092\u8A2D\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addDropdown((dropdown) => dropdown.addOption("ja-JP", "\u65E5\u672C\u8A9E").addOption("en-US", "English").addOption("ko-KR", "\uD55C\uAD6D\uC5B4").addOption("zh-CN", "\u4E2D\u6587\uFF08\u7B80\u4F53\uFF09").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
    }));
  }
};
